/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IrrigationDialog.java
 *
 * Created on Mar 12, 2010, 2:26:14 PM
 */

package xbuild;

import FileXModel.IrrigationApplication;
import FileXModel.FileX;
import FileXModel.ModelXBase;
import FileXModel.Planting;
import FileXModel.Simulation;
import DSSATModel.IrrigationMethod;
import DSSATModel.IrrigationMethodList;
import Extensions.Variables;
import FileXService.FileXValidationService;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.JXFrame;
import xbuild.Components.InputNumberVerifier;
import xbuild.Components.XColumn;

/**
 *
 * @author Jazzy
 */
public class IrrigationDialog extends javax.swing.JDialog implements KeyListener {

    public static class IrrigationTypeItem {
        public Integer code;
        public String description;

        public IrrigationTypeItem(Integer code, String description) {
            this.code = code;
            this.description = description;
        }

        @Override
        public String toString() {
            if (code == 0) {
                return "0";
            }
            return code + " - " + description;
        }
    }

    /** Creates new form IrrigationDialog */
    protected IrrigationApplication irrigApp;
    protected boolean bDay;
    private boolean isOK;
    private org.jdesktop.swingx.JXLabel lbIIRV;

    public IrrigationDialog(java.awt.Frame parent, boolean modal, boolean bDay, IrrigationApplication irrigApp) {
        super(parent, modal);
        initComponents();

        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        Dimension winSize = getSize();
        setLocation((screenWidth - winSize.width) / 2 , (screenHeight - winSize.height) / 2);

        this.irrigApp = irrigApp;
        this.bDay = bDay;

        lbDay.setVisible(bDay);
        txtIDATE.setVisible(bDay);
        lbDate.setVisible(!bDay);
        dpIDATE.setVisible(!bDay);
        jLabel1.setVisible(!bDay);

        txtIDATE.addKeyListener(this);
        dpIDATE.addKeyListener(this);
        txtIRVAL.addKeyListener(this);
        cbIIRV.addKeyListener(this);

        cbIROP.setInit(irrigApp, "IROP", irrigApp.IROP, IrrigationMethodList.GetAll(), 
                new XColumn[] { 
                    new  XColumn("Code", "Code", 100),
                    new  XColumn("Description", "Description", 200)
                }, "Code");
        
        cbIIRV.addItem(new IrrigationTypeItem(0, ""));
        for (DSSATModel.BaseModel method : IrrigationMethodList.GetAll()) {
            try {
                String codeStr = method.Code;
                if (codeStr != null && codeStr.startsWith("IR")) {
                    int num = Integer.parseInt(codeStr.substring(2));
                    cbIIRV.addItem(new IrrigationTypeItem(num, method.Description));
                }
            } catch (Exception ex) {
                // ignore
            }
        }
        
        boolean isRice = isRice();
        lbIIRV.setVisible(isRice);
        cbIIRV.setVisible(isRice);

        cbIROP.addActionListener((java.awt.event.ActionEvent evt) -> {
            if (isRice()) {
                try {
                    Object item = cbIROP.getSelectedItem();
                    if (item instanceof DSSATModel.IrrigationMethod) {
                        String irop = ((DSSATModel.IrrigationMethod) item).Code;
                        if (irop != null && irop.startsWith("IR")) {
                            int numPart = Integer.parseInt(irop.substring(2));
                            for (int i = 0; i < cbIIRV.getItemCount(); i++) {
                                IrrigationTypeItem typeItem = cbIIRV.getItemAt(i);
                                if (typeItem.code == numPart) {
                                    cbIIRV.setSelectedIndex(i);
                                    break;
                                }
                            }
                        }
                    }
                } catch (Exception ex) {
                    // ignore
                }
            }
        });
        
        Load();
        
        isOK = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        lbDay = new org.jdesktop.swingx.JXLabel();
        txtIDATE = new javax.swing.JFormattedTextField();
        lbDate = new org.jdesktop.swingx.JXLabel();
        dpIDATE = new org.jdesktop.swingx.JXDatePicker();
        txtIRVAL = new javax.swing.JFormattedTextField();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        bnOK = new javax.swing.JButton();
        bnCacel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbIROP = new xbuild.Components.XDropdownTableComboBox();
        lbIIRV = new org.jdesktop.swingx.JXLabel();
        cbIIRV = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lbDay.setText("Day");

        txtIDATE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtIDATE.setInputVerifier(new InputNumberVerifier());

        lbDate.setText("Date");

        dpIDATE.setFormats(Variables.getDateFormat());
        dpIDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpIDATEActionPerformed(evt);
            }
        });

        txtIRVAL.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtIRVAL.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIRVAL.setInputVerifier(new InputNumberVerifier());

        jXLabel4.setText("Amount of Water");

        jXLabel5.setText("Operation");

        jXLabel6.setText("mm");

        bnOK.setText("Ok");
        bnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnOKActionPerformed(evt);
            }
        });

        bnCacel.setText("Cancel");
        bnCacel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnCacelActionPerformed(evt);
            }
        });

        jLabel1.setText(Variables.getDateFormatString());

        lbIIRV.setText("Irrigation Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIIRV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbIROP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bnOK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bnCacel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dpIDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtIRVAL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbIIRV, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(182, 182, 182)
                                .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dpIDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIRVAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbIROP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbIIRV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIIRV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnOK)
                    .addComponent(bnCacel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dpIDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpIDATEActionPerformed
        Update();
        boolean isValid = FileXValidationService.isAfterSimulationDate(dpIDATE.getDate());
        if (!isValid) {
            JOptionPane.showMessageDialog(new JXFrame(), "Date is defined prior to the start of simulation date.", "ERROR", 0);
        }
    }//GEN-LAST:event_dpIDATEActionPerformed

    private void bnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnOKActionPerformed
        Update();
        isOK = true;
        dispose();
    }//GEN-LAST:event_bnOKActionPerformed

    private void bnCacelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnCacelActionPerformed
        isOK = false;
        dispose();
    }//GEN-LAST:event_bnCacelActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if(!isOK)
            SetNull();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnCacel;
    private javax.swing.JButton bnOK;
    private javax.swing.JComboBox<IrrigationTypeItem> cbIIRV;
    private xbuild.Components.XDropdownTableComboBox cbIROP;
    private org.jdesktop.swingx.JXDatePicker dpIDATE;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel lbDate;
    private org.jdesktop.swingx.JXLabel lbDay;
    private javax.swing.JFormattedTextField txtIDATE;
    private javax.swing.JFormattedTextField txtIRVAL;
    // End of variables declaration//GEN-END:variables

    public IrrigationApplication GetData()
    {
        return irrigApp;
    }

    public void keyTyped(KeyEvent e) {
        Update();
    }

    public void keyPressed(KeyEvent e) {
        Update();
    }

    public void keyReleased(KeyEvent e) {
        Update();
    }

    protected void Update() {
        if(bDay)
        {
            try
            {
                irrigApp.IDAY = Integer.parseInt(txtIDATE.getText());
            }
            catch(Exception ex)
            {
                irrigApp.IDAY = null;
            }
            irrigApp.IDATE = null;
        }
        else
        {
            try
            {
                irrigApp.IDATE = dpIDATE.getDate();
            }
            catch(Exception ex)
            {
                irrigApp.IDATE = null;
            }
            irrigApp.IDAY = null;
        }
        try
        {
            irrigApp.IRVAL = Float.parseFloat(txtIRVAL.getText());
        }
        catch(Exception ex)
        {
            irrigApp.IRVAL = null;
        }
        if (isRice()) {
            IrrigationTypeItem selected = (IrrigationTypeItem) cbIIRV.getSelectedItem();
            irrigApp.IIRV = selected != null ? selected.code : null;
        } else {
            irrigApp.IIRV = null;
        }
    }

    protected void Load() {
        if(bDay)
        {
            try
            {
                txtIDATE.setText(irrigApp.IDAY.toString());
            }
            catch(Exception ex)
            {
                txtIDATE.setText("");
            }
            dpIDATE.setDate(null);
        }
        else
        {
            if (irrigApp.IDATE == null) {
                java.util.Date defaultDate = null;
                if (FileX.simulationList != null && FileX.simulationList.GetSize() > 0) {
                    for (ModelXBase sim : FileX.simulationList.GetAll()) {
                        Simulation s = (Simulation) sim;
                        if (s.SDATE != null) {
                            defaultDate = s.SDATE;
                            break;
                        }
                    }
                }
                if (defaultDate == null && FileX.plantings != null && FileX.plantings.GetSize() > 0) {
                    for (ModelXBase planting : FileX.plantings.GetAll()) {
                        Planting p = (Planting) planting;
                        if (p.PDATE != null) {
                            defaultDate = p.PDATE;
                            break;
                        }
                    }
                }
                if (defaultDate == null) {
                    defaultDate = xbuild.Components.DefaultDateHelper.getDefaultDate();
                }
                irrigApp.IDATE = defaultDate;
            }
            try
            {
                dpIDATE.setDate(irrigApp.IDATE);
            }
            catch(Exception ex)
            {
                dpIDATE.setDate(null);
            }
            txtIDATE.setText("");
        }
        try
        {
            txtIRVAL.setText(irrigApp.IRVAL.toString());
        }
        catch(Exception ex)
        {
            txtIRVAL.setText("");
        }
        try
        {
            if (irrigApp.IIRV != null) {
                for (int i = 0; i < cbIIRV.getItemCount(); i++) {
                    if (cbIIRV.getItemAt(i).code.equals(irrigApp.IIRV)) {
                        cbIIRV.setSelectedIndex(i);
                        break;
                    }
                }
            } else {
                cbIIRV.setSelectedIndex(0);
            }
        }
        catch(Exception ex)
        {
            cbIIRV.setSelectedIndex(0);
        }
    }

    public void SetNull() {
        irrigApp = null;
    }

    private boolean isRice() {
        if (FileX.general.crop != null && "RI".equals(FileX.general.crop.CropCode)) {
            return true;
        }
        if (FileX.cultivars != null && FileX.cultivars.GetSize() > 0) {
            FileXModel.Cultivar cul = (FileXModel.Cultivar) FileX.cultivars.GetAtIndex(0);
            if ("RI".equals(cul.CR)) {
                return true;
            }
        }
        return false;
    }
}
