/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CultivarListDialog.java
 *
 * Created on Mar 16, 2010, 10:02:02 PM
 */

package ListDialog;

import FileXModel.FileX;
import DSSATModel.Cultivar;
import DSSATModel.CultivarList;
import DSSATModel.ExperimentType;
import Extensions.Utils;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Toolkit;
import java.util.ArrayList;
import xbuild.Components.XColumn;

/**
 *
 * @author Jazzy
 */
public class CultivarListDialog extends javax.swing.JDialog {

    /** Creates new form CultivarListDialog */

    private ArrayList<Cultivar> cultivars;

    public CultivarListDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        Dimension winSize = getSize();
        setLocation((screenWidth - winSize.width) / 2 , (screenHeight - winSize.height) / 2);
        
        AddDataToTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bnOK = new javax.swing.JButton();
        bnCancel = new javax.swing.JButton();
        cbCultivar = new xbuild.Components.XDropdownTableComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bnOK.setText("OK");
        bnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnOKActionPerformed(evt);
            }
        });

        bnCancel.setText("Cancel");
        bnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnCancelActionPerformed(evt);
            }
        });

        cbCultivar.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbCultivarPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 219, Short.MAX_VALUE)
                        .addComponent(bnOK)
                        .addGap(26, 26, 26)
                        .addComponent(bnCancel))
                    .addComponent(cbCultivar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbCultivar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 531, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnOK)
                    .addComponent(bnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnOKActionPerformed
        cultivars = new ArrayList<>();
        
        Cultivar c = (Cultivar)cbCultivar.getSelectedItem();
        cultivars.add(c);
        
        dispose();
    }//GEN-LAST:event_bnOKActionPerformed

    private void bnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnCancelActionPerformed
        SetNull();
        dispose();
    }//GEN-LAST:event_bnCancelActionPerformed

    private void cbCultivarPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbCultivarPopupMenuWillBecomeInvisible
        EventQueue.invokeLater(() -> {            
            Utils.setTimeout(() -> {
                cbCultivar.showPopup();
            }, 1);
        });
    }//GEN-LAST:event_cbCultivarPopupMenuWillBecomeInvisible

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnCancel;
    private javax.swing.JButton bnOK;
    private xbuild.Components.XDropdownTableComboBox cbCultivar;
    // End of variables declaration//GEN-END:variables

    public ArrayList<Cultivar> GetData() {
        return cultivars;
    }

    public void SetNull()
    {
        cultivars = null;
    }

    private void AddDataToTable() {
        if(FileX.general.FileType == ExperimentType.Experimental){
            cbCultivar.setInit(null, "CulCode", "", CultivarList.GetAt(FileX.general.crop), new XColumn[]{new XColumn("CulName", "Cultivar Name", 200)}, "CropCode");
        }
        else{
            cbCultivar.setInit(null, "CulCode", "", CultivarList.GetAll(), new XColumn[]{new XColumn("CropName", "Crop Name", 200), new XColumn("CulName", "Cultivar Name", 200)}, "CropCode");
        }
    
        EventQueue.invokeLater(() -> {
            Utils.setTimeout(() -> {
                cbCultivar.showPopup();
            }, 50);
        });
        
    }
}
