/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WeatherStationDialog.java
 *
 * Created on Mar 14, 2010, 4:33:15 PM
 */

package ListDialog;

import DSSATModel.WeatherStation;
import DSSATModel.WeatherStationList;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Jazzy
 */
public class WeatherStationDialog extends javax.swing.JDialog {

    /** Creates new form WeatherStationDialog */

    private WeatherStation wsta;

    public WeatherStationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        Dimension winSize = getSize();
        setLocation((screenWidth - winSize.width) / 2 , (screenHeight - winSize.height) / 2);

        TableColumnModel tcm = jXTable1.getColumnModel();
        tcm.getColumn(0).setPreferredWidth(200);
        tcm.getColumn(1).setPreferredWidth(screenWidth - 200);
        
        AddDataToTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setModalityType(null);
        setResizable(false);

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "WSTA", "Station Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jXTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jXTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXTable1MouseClicked
        if(evt.getClickCount() == 2) {
            wsta = new WeatherStation();

            TableModel tbModel = jXTable1.getModel();
            int viewRow = jXTable1.getSelectedRow();
            int row = -1;
            if (viewRow < 0) {
                row = viewRow;
            } else {
                row = jXTable1.convertRowIndexToModel(viewRow);
            }
            
            ListSelectionModel sel = jXTable1.getSelectionModel();

            wsta.Code = (String) tbModel.getValueAt(row, 0);
            wsta.StationName = (String) tbModel.getValueAt(row, 1);

            dispose();
        }
    }//GEN-LAST:event_jXTable1MouseClicked

    public WeatherStation GetSelected() {
        return wsta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTable jXTable1;
    // End of variables declaration//GEN-END:variables

    private void AddDataToTable() {
        DefaultTableModel tbModel = (DefaultTableModel) jXTable1.getModel();

//        WeatherStationList.GetAll().forEach(wsta ->
//        {
//            tbModel.addRow(new Object[] {wsta.Code, wsta.StationName});
//        });
    }
    
    public void Filtering(String filter){
        DefaultTableModel tbModel = (DefaultTableModel) jXTable1.getModel();
        while(tbModel.getRowCount() > 0)
            tbModel.removeRow(0);        
        
//        WeatherStationList.GetAll().forEach(wsta ->
//        {
//            if(wsta.Code.toLowerCase().contains(filter.toLowerCase()) || wsta.StationName.toLowerCase().contains(filter.toLowerCase()))
//                tbModel.addRow(new Object[] {wsta.Code, wsta.StationName});
//        });
        
        jXTable1.setModel(tbModel);
    }
}


